create table person
(
    id            integer generated by default as identity
        primary key,
    full_name     varchar(100) not null
        unique,
    year_of_birth integer      not null
);

alter table person
    owner to postgres;

create table book
(
    id         integer generated by default as identity
        primary key,
    title      varchar(100) not null,
    author     varchar(100) not null,
    year       integer      not null,
    person_id  integer
                            references person
                                on delete set null,
    taken_time timestamp
);

alter table book
    owner to postgres;